### ISSUE TITLE
Errors from workers in multiprocessing example

### ISSUE THREAD

**Issue by crd477** [jmswaney/blog#1]
Thanks for the nice multiprocessing blog post.  I'm trying to follow along with it but when I get to method #2, I see errors like the following:
```
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "C:\Users\crd\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\crd\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\crd\Python39\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\crd\Python39\lib\multiprocessing\queues.py", line 368, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_process_image' on <module '__main__' (built-in)>
```
The Jupyter kernel never makes any progress after that point.  I've marked the notebook as "Trusted" and I've tried with both Python 3.8.10 and Python 3.9.5, both on Windows.  Have you seen this before?
Thanks again...

**Comment by jmswaney** [comment]
Hey, sorry I just saw this. It seems the spawned processes in the multiprocessing pool don't have access to the `_process_image` function defined in that cell. Other's have had similar problems [here](https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror)

You can try the advice there to move the `_process_image` function into a separate `.py` module to import. I wouldn't be surprised if this is only an issue on Windows because of the OS differences that the multiprocessing module tries to abstract away from the developer.

**Comment by crd477** [comment]
Thanks for the reply.  That solution worked!
